# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [13]:
# No code solution (reading)
import torch
print(torch.__version__)

1.13.1


### 2. Create a random tensor with shape `(7, 7)`.


In [15]:

# Import torch
import torch 

# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape # prints tensor and checks if shape is (7,7)

(tensor([[5.0571e-02, 5.7589e-01, 5.4871e-02, 2.6069e-01, 8.6417e-01, 8.9454e-01,
          1.0751e-01],
         [7.3451e-01, 8.8422e-01, 9.8725e-02, 8.3735e-03, 3.2866e-04, 4.0468e-01,
          2.6971e-01],
         [9.9634e-01, 5.1017e-01, 4.2896e-01, 3.9726e-01, 3.7460e-01, 4.6248e-01,
          8.0545e-01],
         [4.5732e-02, 1.1274e-01, 3.8208e-01, 9.7780e-01, 7.6166e-01, 3.2607e-01,
          1.1918e-01],
         [9.7898e-01, 4.4270e-01, 6.8058e-01, 2.6726e-02, 5.7557e-01, 9.3450e-01,
          5.6559e-01],
         [7.3381e-01, 1.8684e-01, 1.1211e-01, 8.9850e-01, 3.1985e-01, 6.8386e-01,
          1.4262e-01],
         [3.4057e-01, 2.9078e-01, 8.6023e-01, 5.4859e-01, 6.3642e-01, 6.3774e-02,
          3.1030e-03]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [29]:
import torch

# Create another random tensor
Y = torch.rand(size=(1,7)) # creates another random tensor 
Z = torch.matmul(X,Y.T) # reshapes/transposes original tensor 

# Perform matrix multiplication 
Z # matmul fucntion performances multiplication 

tensor([[0.8187],
        [1.1814],
        [1.8323],
        [1.0085],
        [1.8666],
        [1.2952],
        [1.4307]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [32]:
import torch

# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7,7))
Y = torch.rand(size=(1,7)) # creates another random tensor 

# Matrix multiply tensors
Z = torch.matmul(X,Y.T) # reshapes/transposes original tensor 
Z #prints z

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [34]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [38]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device: {device}")

# Create two random tensors on GPU
X = torch.rand(size=(2,3)).to(device)
Y = torch.rand(size=(2,3)).to(device)
X, Y

device: cpu


(tensor([[0.8579, 0.6870, 0.0051],
         [0.1757, 0.7497, 0.6047]]),
 tensor([[0.1100, 0.2121, 0.9704],
         [0.8369, 0.2820, 0.3742]]))

In [39]:
# answer


# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B
     

Device: cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [42]:
# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [48]:
# Find max
print(f"max: {tensor_C.max()}")

# Find min
print(f"minimum: {tensor_C.min()}")




max: 0.5617256760597229
minimum: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [49]:
# Find arg max
print(f"max: {tensor_C.argmax()}")

# Find arg min
print(f"min: {tensor_C.argmin()}")

max: 3
min: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [53]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(size=(1,1,1,10))


# Remove single dimensions
tensor2 = tensor.squeeze() # squeeze function removes 1s 

# Print out tensors and their shapes
print(tensor, tensor.shape) 
print(tensor2, tensor2.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
